---
title: "BUSTED_ANALYSIS_3X3"
author: "sadie"
date: "1/28/2020"
output:
  pdf_document: default
  html_document: default
---

load libraries
```{r libraries, include=FALSE}
#libraries used
library(dplyr)
library(stringr)
library(ggplot2)
library(readr)
library(emdbook)
library(reshape2)
library(ape)
library(phytools)
```

read in data
```{r}
#add rate category count and order and gene for each file (can be found in file name FILE)

mtDNA_SRV_3x3_1_27_2020 <- read_csv("~/bin/mtDNA_redo/data/mtDNA_SRV_3x3_1_27_2020") 
mtDNA_SRV_3x3_1_27_2020 <- mtDNA_SRV_3x3_1_27_2020 %>% 
  mutate(., 
         NS.rates = 3,
         S.rates = 3,
         order = str_extract_all(mtDNA_SRV_3x3_1_27_2020$FILE, "\\w+(?=-)", simplify = T)[,1],
         gene = str_extract_all(mtDNA_SRV_3x3_1_27_2020$FILE, "\\w+(?=-)", simplify = T)[,2])

mtDNA_BUSTED_3x3_1_27_2020 <- read_csv("~/bin/mtDNA_redo/data/mtDNA_BUSTED_3x3_1_27_2020")
mtDNA_BUSTED_3x3_1_27_2020<- mtDNA_BUSTED_3x3_1_27_2020 %>%  mutate(., NS.rates = 3,
          S.rates = 3,
          order = str_extract_all(mtDNA_BUSTED_3x3_1_27_2020$FILE, "\\w+(?=-)", simplify = T)[,1],
            gene = str_extract_all(mtDNA_BUSTED_3x3_1_27_2020$FILE, "\\w+(?=-)", simplify = T)[,2])

#these are the orders used in the original analysis
orders_used <- read_delim("~/bin/mtDNA_redo/data/actual_orders_used.txt", delim = "\n", col_names = FALSE)

```
```{r}
mtDNA_3x3 <- full_join(mtDNA_BUSTED_3x3_1_27_2020, mtDNA_SRV_3x3_1_27_2020, by = c("FILE", "Sites", "Sequences", "gene", "order", "NS.rates","S.rates"), suffix = c(".busted",".srv"))


#test_row <- bind_rows(mtDNA_BUSTED_3x3_1_27_2020, mtDNA_SRV_3x3_1_27_2020)
```

```{r}
mtDNA_3x3$gene= toupper(mtDNA_3x3$gene)
mtDNA_3x3$order = toupper(mtDNA_3x3$order)

#fix some mispellings of order names
mtDNA_3x3$order[which(mtDNA_3x3$order == "CHIMAERIFORMS")]<-"CHIMAERIFORMES"
mtDNA_3x3$order[which(mtDNA_3x3$order == "CARNIVORES")] <-"CARNIVORA"
mtDNA_3x3$order[which(mtDNA_3x3$order == "GASTEROSTEIFORMES")] <-"GASTEROSTEALES"
```

how many genes per orders originally
```{r}
count(mtDNA_3x3, groups = order) -> temp
temp
temp %>% filter(n >=12)
```


```{r}
#filter based on orders previously used:
mtDNA_3x3 <- mtDNA_3x3 %>% filter(order %in% orders_used$X1)
```



```{r}
syn_labels <- list("Synonymous.CV"="A) Synonymous CV",
                   "NS.CV" = "B) Nonsynoymous CV BUSTED[S]",
                   "CV.NSRV.busted" = "C) Nonsynoymous CV BUSTED")

syn_labeller <- function(variable,value){
  return(syn_labels[value])
}
```

boxplots of the CVs grouped by genes
```{r}
num_orders_per_gene = mtDNA_3x3  %>% count(gene)
gene_boxplots <- mtDNA_3x3 %>% select(CV.SRV, CV.NSRV.srv, CV.NSRV.busted,gene)
gene_boxplots <-gene_boxplots %>% melt(id.vars = "gene")




gene_boxplots %>%ggplot(aes(gene, value))+
  geom_boxplot()+ facet_grid(~variable,labeller = syn_labeller)+
  #coord_cartesian(ylim = c(0,3.5))+
  ylab("CV")+xlab("Gene")+ theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_x_discrete(labels = paste(num_orders_per_gene$gene, num_orders_per_gene$n, sep = " N = "))

```

```{r}
mtDNA_3x3 %>% ggplot()+geom_point(aes(CV.SRV, CV.NSRV.srv))+ xlab("Synonymous CV")+
  ylab("Nonsynonymous CV")+ theme_bw()+
  geom_abline(slope = 1, intercept = 0, color = 'blue') +
  geom_abline(slope = 2, intercept = 0,color='red', linetype = "dashed" )
#+
 # coord_cartesian(ylim = c(0,3.5), xlim = c(0,1.65))
```

```{r}
source("/Volumes/GoogleDrive/My Drive/BUSTED-SRV/R/useful_functions.R")
gen.sig.table(mtDNA_3x3)
```

boxplots via order tree
```{r}
#read u=in the tree with ape
class.order.tree <- read.tree(file = "~/bin/mtDNA_redo/data/phyliptree_order_class.phy")
tip_labels = toupper(class.order.tree$tip.label)
class.order.tree$tip.label <- tip_labels
mtDNA_3x3$order <-factor(mtDNA_3x3$order, levels = tip_labels)
Syn.CV.mtDNA_3x3= mtDNA_3x3 %>% select(CV.SRV)
names.Syn.CV.mtDNA_3x3 = mtDNA_3x3 %>% select(order)

Syn.CV.mtDNA_3x3 = as.vector(as.matrix(Syn.CV.mtDNA_3x3))
names.Syn.CV.mtDNA_3x3 = as.vector(as.matrix(names.Syn.CV.mtDNA_3x3))
# for(i in 1:length(new_labels)){
# names.Syn.CV.mtDNA_3x3   =str_replace_all(names.Syn.CV.mtDNA_3x3, pattern=num_genes_per_order$Order[i],new_labels[i])
# }
names(Syn.CV.mtDNA_3x3) = names.Syn.CV.mtDNA_3x3

NonSyn.CV.mtDNA_3x3 = mtDNA_3x3 %>% select(CV.NSRV.srv)
names.nonSyn.CV.mtDNA_3x3 = mtDNA_3x3 %>% select(order)

NonSyn.CV.mtDNA_3x3 = as.vector(as.matrix(NonSyn.CV.mtDNA_3x3))
names.nonSyn.CV.mtDNA_3x3 = as.vector(as.matrix(names.nonSyn.CV.mtDNA_3x3))
names(NonSyn.CV.mtDNA_3x3) = names.Syn.CV.mtDNA_3x3

#pdf("tree.pdf", height = 11, width = 8.5)
plotTree(class.order.tree)
#dev.off()

#win.metafile("Images/tree.wmf", height = 11, width = 8.5)
plotTree(class.order.tree)
#dev.off()

class.order.tree$edge.length =NULL
#generate SYNCV tree and box plot
#png(filename = "Images/tree_syn_order.png", width = 500, height = 800)
plotTree.boxplot(class.order.tree, Syn.CV.mtDNA_3x3,
                 args.plotTree = list(fsize = c(0.6)),
                 args.boxplot=list(main = "Synonymous CV 7x10", xlab = "CV"))
#dev.off()
#generate nonsynCV tree and box plot
#png(filename = "Images/tree_nonsyn_order.png",width = 500, height = 800)
plotTree.boxplot(class.order.tree, NonSyn.CV.mtDNA_3x3, 
                 args.plotTree = list(fsize = 0.6),
                 args.boxplot=list(main = "Nonsynonymous CV 7x10"))
#dev.off()

```

```{r}
###order boxplots w/o tree
num_gene_per_order <- mtDNA_3x3 %>% count(order)
order_boxplots <-mtDNA_3x3 %>% select(CV.SRV, CV.NSRV.srv, order)
order_boxplots <- order_boxplots %>% melt(id.vars = "order")

syn_labels <- list("Synonymous.CV"="A) Synonymous CV",
                   "NS.CV" = "B) Nonsynoymous CV")

syn_labeller <- function(variable,value){
  return(syn_labels[value])
}

#png(filename = "Images/no_tree_order_boxplots.png", height = 6, width = 8,res = 700, units="in")
order_boxplots %>%ggplot(aes(order, value))+
  geom_boxplot()+ facet_wrap(~variable,labeller = syn_labeller, nrow = 2)+
  #coord_cartesian(ylim = c(0,3.5))+
  theme_bw()+ ylab("CV")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_x_discrete(labels = paste(num_gene_per_order$order, num_gene_per_order$n, sep = " N = "))
#dev.off()

#win.metafile(filename = "Images/no_tree_order_boxplots.wmf", height = 6, width = 10)
order_boxplots %>%ggplot(aes(order, value))+
  geom_boxplot()+ facet_wrap(~variable,labeller = syn_labeller, nrow = 2)+coord_cartesian(ylim = c(0,3.5))+
  theme_bw()+ ylab("CV")+
theme(axis.text.x = element_text(angle = 65, vjust = 1, hjust=1))+
  scale_x_discrete(labels =num_gene_per_order$Order)
#dev.off()
```

```{r}
mtDNA_3x3 %>% ggplot()+geom_point(aes(CV.SRV, BUSTED.SRV.P))+ xlab("Synonymous CV")+
  ylab("BUSTED[S] P")+ theme_bw()

mtDNA_3x3 %>% ggplot()+geom_point(aes(CV.NSRV.srv, BUSTED.SRV.P))+ xlab("Nonsynonymous CV")+
  ylab("BUSTED[S] P")+ theme_bw()

mtDNA_3x3 %>% ggplot()+geom_point(aes(CV.SRV, BUSTED.P))+ xlab("Synonymous CV")+
  ylab("BUSTED P")+ theme_bw()
```


# Likelihood ratio calculation for Unconstrained log likelihood between BUSTED (H0) and BUSTED[S] (HA)
```{r}
stats = data.frame(File = "",order ="", gene = "", LRT.D = as.numeric(NA), p = as.numeric(NA), stringsAsFactors = F)

#stats =data.frame(File = files, LRT.D = as.numeric(NA), p = as.numeric(NA), stringsAsFactors = F )

#need to make sure things match up 
k=1
n=1
for(n in seq(1,nrow(mtDNA_3x3)-1,by=1)){
  
  D = -2*(mtDNA_3x3$BUSTED.UNLogL[n]-mtDNA_3x3$BUSTED.SRV.UNLogL[n])
  if(as.numeric(D) >= 0 ){
  p =1-pchibarsq(as.numeric(D), df = 1, mix =0.5)
  }
  stats[k,] = c(mtDNA_3x3$FILE[n],mtDNA_3x3$order[n],mtDNA_3x3$gene[n], D, p)
 D = NA
 p = NA
  k=k+1
}
stats$LRT.D = as.numeric(stats$LRT.D)
stats$p = as.numeric(stats$p)
#stats = stats %>% mutate(sort = paste(File, sep = "_"))

print(stats)

```
```{r}
#set up crit values
N <- nrow(stats)/3
crit.p.05 <- 0.05/N
crit.p.01 <- 0.01/N


#number of sig datasets
stats %>% filter(p <= crit.p.01)  %>%nrow
stats %>% filter(p <= crit.p.05)  %>%nrow

#make sig table
sig_table <- stats %>% select(order,gene, p)

#sig_table <- mutate(sig_table,fill = "NA")

sig_table <- mutate(sig_table,fill = "-",ordering = "-",text_size="a")

sig_table$fill[which(sig_table$p>crit.p.05)] <- "-"
sig_table$fill[which(sig_table$p<=crit.p.05)] <-  "*"  #"Sig at alpha = 0.05"
sig_table$fill[which(sig_table$p<=crit.p.01)] <- "**" #"Sig at alpha = 0.01"

sig_table$ordering[which(sig_table$p>crit.p.05)] <- "-"
sig_table$ordering[which(sig_table$p<=crit.p.05)] <- "*"
sig_table$ordering[which(sig_table$p<=crit.p.01)] <- "**"

sig_table$text_size[which(!is.na(sig_table$ordering))] <-"b"

tip_labels = toupper(class.order.tree$tip.label)
sig_table$order = factor(sig_table$order, levels = tip_labels)

sig_table %>% ggplot(aes(x=order,y=gene, fill = ordering))+
  geom_tile(size =0.5,na.rm=TRUE,color="black")+ 
  scale_fill_manual(values = c("#FFFFFF","#CCCCCC","#999999"))+
  geom_text(aes(label =fill,size=text_size))+ scale_size_manual(values = c(1.75,3),guide =FALSE)+
  theme(panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 1, hjust=1))+
  coord_fixed(ratio=1)
```

